apiVersion: gitisking/v1
version: v2.1.0
env: dev
metadata:
  name: stock-service
  version: v2.1.0
  repo: https://github.com/ARAldhafeeri/pricing-service-config.git
  devBaseURL: https://localhost:3000/pricing/dev/
  stageBaseURL: https://localhost:3000/pricing/stage/
  prodBaseURL: https://localhost:3000/pricing/prod/
  language: nodejs
  description: Manages product pricing and discount rates.
actualState:
  lastChecked: 2024-09-23T23:37:34.942Z
  handshakeStatus: true
  details:
    stockService:
      status: true
      message: Handshake successful with stockService
    restockService:
      status: true
      message: Handshake successful with restockService
desiredState:
  stockService:
    sync: strict
    repo: https://github.com/ARAldhafeeri/stock-service-config.git
    dependencies:
      - uuid: 0a22b5d9-0940
        name: stockService
  restockService:
    sync: strict
    repo: https://github.com/ARAldhafeeri/restock-service-config.git
    dependencies:
      - uuid: 0a22b5d9-0941
        name: restockService
